# Meta
description: Private theme for artifact.me
keywords: hexo,theme,artifact,otakism

# Author
author_avatar: /img/avatar.gif

# Copyright config
copyright:
  url: https://creativecommons.org/licenses/by-nc-nd/4.0/
  text: 本博客所有文章除特别声明外，均采用 CC BY-NC-ND 4.0 许可协议。转载请注明出处！

# Search
search: 
  enable: false
  service: hexo # swiftype/google/hexo/algolia/azure
  # google 
  google_api_key: 
  google_engine_id: 
  # algolia
  algolia_app_id: 
  algolia_api_key: 
  algolia_index_name: 
  # azure
  azure_service_name: 
  azure_index_name: 
  azure_query_key: 

# Miscellaneous
google_analytics: 
favicon: /favicon.png

# Less
less:
  compress: true

# Music service by Meting
music: false

# use url, not username
social:
- name: feed
	url: /atom.xml
- name: email
  icon: mail
  url: 
- name: github
  url: https://github.com/artchen
- name: twitter
  url: 
- name: google
  url: 
- name: facebook
  url: 
- name: linkedin
  url: 
- name: weibo
  url: 
- name: tumblr
  url: 
- name: dribbble
  url: 
- name: pinterest
  url: 
- name: instagram
  url: 
- name: behance
  url: 
